version: "3.9"

services:
  db:
    container_name: mysqlDb
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: educonectedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  adminer:
    container_name: adminer
    build:
      context: .
      dockerfile: Dockerfile.adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

volumes:
  db-data:

    null
networks:
  backend: null
